export const mock1DayForecast = {
  Headline: {
    EffectiveDate: "2023-09-08T08:00:00+01:00",
    EffectiveEpochDate: 1694156400,
    Severity: 5,
    Text: "Possible danger of dehydration and heat stroke while doing strenuous activities Friday",
    Category: "heat",
    EndDate: "2023-09-08T20:00:00+01:00",
    EndEpochDate: 1694199600,
    MobileLink:
      "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?lang=en-us",
    Link: "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?lang=en-us",
  },
  DailyForecasts: [
    {
      Date: "2023-09-06T07:00:00+01:00",
      EpochDate: 1693980000,
      Sun: {
        Rise: "2023-09-06T06:20:00+01:00",
        EpochRise: 1693977600,
        Set: "2023-09-06T19:37:00+01:00",
        EpochSet: 1694025420,
      },
      Moon: {
        Rise: "2023-09-06T22:12:00+01:00",
        EpochRise: 1694034720,
        Set: "2023-09-07T16:05:00+01:00",
        EpochSet: 1694099100,
        Phase: "Last",
        Age: 21,
      },
      Temperature: {
        Minimum: {
          Value: 18.9,
          Unit: "C",
          UnitType: 17,
        },
        Maximum: {
          Value: 30.6,
          Unit: "C",
          UnitType: 17,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 18.3,
          Unit: "C",
          UnitType: 17,
          Phrase: "Pleasant",
        },
        Maximum: {
          Value: 32.2,
          Unit: "C",
          UnitType: 17,
          Phrase: "Hot",
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 18.3,
          Unit: "C",
          UnitType: 17,
          Phrase: "Pleasant",
        },
        Maximum: {
          Value: 29.4,
          Unit: "C",
          UnitType: 17,
          Phrase: "Very Warm",
        },
      },
      HoursOfSun: 7.8,
      DegreeDaySummary: {
        Heating: {
          Value: 0,
          Unit: "C",
          UnitType: 17,
        },
        Cooling: {
          Value: 7,
          Unit: "C",
          UnitType: 17,
        },
      },
      AirAndPollen: [
        {
          Name: "AirQuality",
          Value: 0,
          Category: "Good",
          CategoryValue: 1,
          Type: "Ozone",
        },
        {
          Name: "Grass",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Mold",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Tree",
          Value: 2,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Ragweed",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "UVIndex",
          Value: 4,
          Category: "Moderate",
          CategoryValue: 2,
        },
      ],
      Day: {
        Icon: 1,
        IconPhrase: "Sunny",
        HasPrecipitation: false,
        ShortPhrase: "Sunny and very warm",
        LongPhrase: "Sunny and very warm",
        PrecipitationProbability: 1,
        ThunderstormProbability: 0,
        RainProbability: 1,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 8,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 63,
            Localized: "ENE",
            English: "ENE",
          },
        },
        WindGust: {
          Speed: {
            Value: 16.1,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 63,
            Localized: "ENE",
            English: "ENE",
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: "mm",
          UnitType: 3,
        },
        Rain: {
          Value: 0,
          Unit: "mm",
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: "cm",
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: "mm",
          UnitType: 3,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 10,
        Evapotranspiration: {
          Value: 4.1,
          Unit: "mm",
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 8613.9,
          Unit: "W/m²",
          UnitType: 33,
        },
      },
      Night: {
        Icon: 35,
        IconPhrase: "Partly cloudy",
        HasPrecipitation: false,
        ShortPhrase: "Warm with patchy clouds",
        LongPhrase: "Warm with patchy clouds",
        PrecipitationProbability: 1,
        ThunderstormProbability: 0,
        RainProbability: 1,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 8,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 70,
            Localized: "ENE",
            English: "ENE",
          },
        },
        WindGust: {
          Speed: {
            Value: 19.3,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 70,
            Localized: "ENE",
            English: "ENE",
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: "mm",
          UnitType: 3,
        },
        Rain: {
          Value: 0,
          Unit: "mm",
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: "cm",
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: "mm",
          UnitType: 3,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 43,
        Evapotranspiration: {
          Value: 0.3,
          Unit: "mm",
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 249.8,
          Unit: "W/m²",
          UnitType: 33,
        },
      },
      Sources: ["AccuWeather"],
      MobileLink:
        "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=1&unit=c&lang=en-us",
      Link: "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=1&unit=c&lang=en-us",
    },
  ],
};

export const mock5DayForecast = {
  Headline: {
    EffectiveDate: "2023-09-08T08:00:00+01:00",
    EffectiveEpochDate: 1694156400,
    Severity: 5,
    Text: "Possible danger of dehydration and heat stroke while doing strenuous activities Friday",
    Category: "heat",
    EndDate: "2023-09-08T20:00:00+01:00",
    EndEpochDate: 1694199600,
    MobileLink:
      "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?lang=en-us",
    Link: "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?lang=en-us",
  },
  DailyForecasts: [
    {
      Date: "2023-09-06T07:00:00+01:00",
      EpochDate: 1693980000,
      Temperature: {
        Minimum: {
          Value: 66,
          Unit: "F",
          UnitType: 18,
        },
        Maximum: {
          Value: 87,
          Unit: "F",
          UnitType: 18,
        },
      },
      Day: {
        Icon: 1,
        IconPhrase: "Sunny",
        HasPrecipitation: false,
      },
      Night: {
        Icon: 35,
        IconPhrase: "Partly cloudy",
        HasPrecipitation: false,
      },
      Sources: ["AccuWeather"],
      MobileLink:
        "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=1&lang=en-us",
      Link: "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=1&lang=en-us",
    },
    {
      Date: "2023-09-07T07:00:00+01:00",
      EpochDate: 1694066400,
      Temperature: {
        Minimum: {
          Value: 62,
          Unit: "F",
          UnitType: 18,
        },
        Maximum: {
          Value: 87,
          Unit: "F",
          UnitType: 18,
        },
      },
      Day: {
        Icon: 5,
        IconPhrase: "Hazy sunshine",
        HasPrecipitation: false,
      },
      Night: {
        Icon: 36,
        IconPhrase: "Intermittent clouds",
        HasPrecipitation: false,
      },
      Sources: ["AccuWeather"],
      MobileLink:
        "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=2&lang=en-us",
      Link: "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=2&lang=en-us",
    },
    {
      Date: "2023-09-08T07:00:00+01:00",
      EpochDate: 1694152800,
      Temperature: {
        Minimum: {
          Value: 66,
          Unit: "F",
          UnitType: 18,
        },
        Maximum: {
          Value: 88,
          Unit: "F",
          UnitType: 18,
        },
      },
      Day: {
        Icon: 3,
        IconPhrase: "Partly sunny",
        HasPrecipitation: false,
      },
      Night: {
        Icon: 36,
        IconPhrase: "Intermittent clouds",
        HasPrecipitation: false,
      },
      Sources: ["AccuWeather"],
      MobileLink:
        "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=3&lang=en-us",
      Link: "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=3&lang=en-us",
    },
    {
      Date: "2023-09-09T07:00:00+01:00",
      EpochDate: 1694239200,
      Temperature: {
        Minimum: {
          Value: 68,
          Unit: "F",
          UnitType: 18,
        },
        Maximum: {
          Value: 91,
          Unit: "F",
          UnitType: 18,
        },
      },
      Day: {
        Icon: 3,
        IconPhrase: "Partly sunny",
        HasPrecipitation: false,
      },
      Night: {
        Icon: 35,
        IconPhrase: "Partly cloudy",
        HasPrecipitation: false,
      },
      Sources: ["AccuWeather"],
      MobileLink:
        "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=4&lang=en-us",
      Link: "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=4&lang=en-us",
    },
    {
      Date: "2023-09-10T07:00:00+01:00",
      EpochDate: 1694325600,
      Temperature: {
        Minimum: {
          Value: 65,
          Unit: "F",
          UnitType: 18,
        },
        Maximum: {
          Value: 87,
          Unit: "F",
          UnitType: 18,
        },
      },
      Day: {
        Icon: 4,
        IconPhrase: "Intermittent clouds",
        HasPrecipitation: false,
      },
      Night: {
        Icon: 36,
        IconPhrase: "Intermittent clouds",
        HasPrecipitation: false,
      },
      Sources: ["AccuWeather"],
      MobileLink:
        "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=5&lang=en-us",
      Link: "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=5&lang=en-us",
    },
  ],
};

export const mockedLocationsResponse = [
  {
    Version: 1,
    Key: "1325849",
    Type: "City",
    Rank: 600,
    LocalizedName: "Londo",
    EnglishName: "Londo",
    PrimaryPostalCode: "",
    Region: {
      ID: "SAM",
      LocalizedName: "South America",
      EnglishName: "South America",
    },
    Country: {
      ID: "BO",
      LocalizedName: "Bolivia",
      EnglishName: "Bolivia",
    },
    AdministrativeArea: {
      ID: "C",
      LocalizedName: "Cochabamba",
      EnglishName: "Cochabamba",
      Level: 1,
      LocalizedType: "Department",
      EnglishType: "Department",
      CountryID: "BO",
    },
    TimeZone: {
      Code: "BOT",
      Name: "America/La_Paz",
      GmtOffset: -4,
      IsDaylightSaving: false,
      NextOffsetChange: null,
    },
    GeoPosition: {
      Latitude: -17.6,
      Longitude: -66.283,
      Elevation: {
        Metric: {
          Value: 2432,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 7980,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "FutureRadar",
      "MinuteCast",
      "Radar",
    ],
  },
  {
    Version: 1,
    Key: "911799",
    Type: "City",
    Rank: 600,
    LocalizedName: "Londo",
    EnglishName: "Londo",
    PrimaryPostalCode: "",
    Region: {
      ID: "AFR",
      LocalizedName: "Africa",
      EnglishName: "Africa",
    },
    Country: {
      ID: "CD",
      LocalizedName: "Democratic Republic of the Congo",
      EnglishName: "Democratic Republic of the Congo",
    },
    AdministrativeArea: {
      ID: "TO",
      LocalizedName: "Tshopo",
      EnglishName: "Tshopo",
      Level: 1,
      LocalizedType: "Province",
      EnglishType: "Province",
      CountryID: "CD",
    },
    TimeZone: {
      Code: "CAT",
      Name: "Africa/Lubumbashi",
      GmtOffset: 2,
      IsDaylightSaving: false,
      NextOffsetChange: null,
    },
    GeoPosition: {
      Latitude: 2.05,
      Longitude: 25.717,
      Elevation: {
        Metric: {
          Value: 457,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 1498,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "MinuteCast",
    ],
  },
  {
    Version: 1,
    Key: "497744",
    Type: "City",
    Rank: 600,
    LocalizedName: "Londo",
    EnglishName: "Londo",
    PrimaryPostalCode: "",
    Region: {
      ID: "AFR",
      LocalizedName: "Africa",
      EnglishName: "Africa",
    },
    Country: {
      ID: "CM",
      LocalizedName: "Cameroon",
      EnglishName: "Cameroon",
    },
    AdministrativeArea: {
      ID: "LT",
      LocalizedName: "Littoral",
      EnglishName: "Littoral",
      Level: 1,
      LocalizedType: "Province",
      EnglishType: "Province",
      CountryID: "CM",
    },
    TimeZone: {
      Code: "WAT",
      Name: "Africa/Douala",
      GmtOffset: 1,
      IsDaylightSaving: false,
      NextOffsetChange: null,
    },
    GeoPosition: {
      Latitude: 4.267,
      Longitude: 9.7,
      Elevation: {
        Metric: {
          Value: 1,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 3,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "MinuteCast",
    ],
  },
  {
    Version: 1,
    Key: "1133725",
    Type: "City",
    Rank: 600,
    LocalizedName: "Londo",
    EnglishName: "Londo",
    PrimaryPostalCode: "",
    Region: {
      ID: "AFR",
      LocalizedName: "Africa",
      EnglishName: "Africa",
    },
    Country: {
      ID: "GA",
      LocalizedName: "Gabon",
      EnglishName: "Gabon",
    },
    AdministrativeArea: {
      ID: "7",
      LocalizedName: "Ogooué-Lolo",
      EnglishName: "Ogooué-Lolo",
      Level: 1,
      LocalizedType: "Province",
      EnglishType: "Province",
      CountryID: "GA",
    },
    TimeZone: {
      Code: "WAT",
      Name: "Africa/Libreville",
      GmtOffset: 1,
      IsDaylightSaving: false,
      NextOffsetChange: null,
    },
    GeoPosition: {
      Latitude: -0.933,
      Longitude: 12.817,
      Elevation: {
        Metric: {
          Value: 279,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 915,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "MinuteCast",
    ],
  },
  {
    Version: 1,
    Key: "1437961",
    Type: "City",
    Rank: 600,
    LocalizedName: "Londo",
    EnglishName: "Londo",
    PrimaryPostalCode: "",
    Region: {
      ID: "ASI",
      LocalizedName: "Asia",
      EnglishName: "Asia",
    },
    Country: {
      ID: "MM",
      LocalizedName: "Myanmar",
      EnglishName: "Myanmar",
    },
    AdministrativeArea: {
      ID: "17",
      LocalizedName: "Shan",
      EnglishName: "Shan",
      Level: 1,
      LocalizedType: "State",
      EnglishType: "State",
      CountryID: "MM",
    },
    TimeZone: {
      Code: "MMT",
      Name: "Asia/Rangoon",
      GmtOffset: 6.5,
      IsDaylightSaving: false,
      NextOffsetChange: null,
    },
    GeoPosition: {
      Latitude: 20.15,
      Longitude: 96.683,
      Elevation: {
        Metric: {
          Value: 1398,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 4588,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Taunggyi",
        EnglishName: "Taunggyi",
      },
      {
        Level: 3,
        LocalizedName: "Pinlaung",
        EnglishName: "Pinlaung",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "FutureRadar",
      "MinuteCast",
    ],
  },
  {
    Version: 1,
    Key: "1089837",
    Type: "City",
    Rank: 600,
    LocalizedName: "Londo",
    EnglishName: "Londo",
    PrimaryPostalCode: "",
    Region: {
      ID: "AFR",
      LocalizedName: "Africa",
      EnglishName: "Africa",
    },
    Country: {
      ID: "MW",
      LocalizedName: "Malawi",
      EnglishName: "Malawi",
    },
    AdministrativeArea: {
      ID: "N",
      LocalizedName: "Northern Region",
      EnglishName: "Northern Region",
      Level: 1,
      LocalizedType: "Region",
      EnglishType: "Region",
      CountryID: "MW",
    },
    TimeZone: {
      Code: "CAT",
      Name: "Africa/Blantyre",
      GmtOffset: 2,
      IsDaylightSaving: false,
      NextOffsetChange: null,
    },
    GeoPosition: {
      Latitude: -11.033,
      Longitude: 34.217,
      Elevation: {
        Metric: {
          Value: 472,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 1548,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Lake Nyasa",
        EnglishName: "Lake Nyasa",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "MinuteCast",
    ],
  },
  {
    Version: 1,
    Key: "1488964",
    Type: "City",
    Rank: 600,
    LocalizedName: "Londo",
    EnglishName: "Londo",
    PrimaryPostalCode: "",
    Region: {
      ID: "AFR",
      LocalizedName: "Africa",
      EnglishName: "Africa",
    },
    Country: {
      ID: "MZ",
      LocalizedName: "Mozambique",
      EnglishName: "Mozambique",
    },
    AdministrativeArea: {
      ID: "A",
      LocalizedName: "Niassa",
      EnglishName: "Niassa",
      Level: 1,
      LocalizedType: "Province",
      EnglishType: "Province",
      CountryID: "MZ",
    },
    TimeZone: {
      Code: "CAT",
      Name: "Africa/Maputo",
      GmtOffset: 2,
      IsDaylightSaving: false,
      NextOffsetChange: null,
    },
    GeoPosition: {
      Latitude: -11.946,
      Longitude: 35.065,
      Elevation: {
        Metric: {
          Value: 822,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 2696,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Lago",
        EnglishName: "Lago",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "MinuteCast",
    ],
  },
  {
    Version: 1,
    Key: "1488963",
    Type: "City",
    Rank: 600,
    LocalizedName: "Londo",
    EnglishName: "Londo",
    PrimaryPostalCode: "",
    Region: {
      ID: "AFR",
      LocalizedName: "Africa",
      EnglishName: "Africa",
    },
    Country: {
      ID: "MZ",
      LocalizedName: "Mozambique",
      EnglishName: "Mozambique",
    },
    AdministrativeArea: {
      ID: "P",
      LocalizedName: "Cabo Delgado",
      EnglishName: "Cabo Delgado",
      Level: 1,
      LocalizedType: "Province",
      EnglishType: "Province",
      CountryID: "MZ",
    },
    TimeZone: {
      Code: "CAT",
      Name: "Africa/Maputo",
      GmtOffset: 2,
      IsDaylightSaving: false,
      NextOffsetChange: null,
    },
    GeoPosition: {
      Latitude: -12.883,
      Longitude: 40.5,
      Elevation: {
        Metric: {
          Value: 1,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 3,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Pemba",
        EnglishName: "Pemba",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "MinuteCast",
    ],
  },
  {
    Version: 1,
    Key: "851067",
    Type: "City",
    Rank: 600,
    LocalizedName: "Londo",
    EnglishName: "Londo",
    PrimaryPostalCode: "",
    Region: {
      ID: "OCN",
      LocalizedName: "Oceania",
      EnglishName: "Oceania",
    },
    Country: {
      ID: "PG",
      LocalizedName: "Papua New Guinea",
      EnglishName: "Papua New Guinea",
    },
    AdministrativeArea: {
      ID: "EPW",
      LocalizedName: "Enga",
      EnglishName: "Enga",
      Level: 1,
      LocalizedType: "Province",
      EnglishType: "Province",
      CountryID: "PG",
    },
    TimeZone: {
      Code: "PGT",
      Name: "Pacific/Port_Moresby",
      GmtOffset: 10,
      IsDaylightSaving: false,
      NextOffsetChange: null,
    },
    GeoPosition: {
      Latitude: -5.667,
      Longitude: 143.867,
      Elevation: {
        Metric: {
          Value: 1928,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 6327,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "FutureRadar",
      "MinuteCast",
    ],
  },
  {
    Version: 1,
    Key: "725068",
    Type: "City",
    Rank: 600,
    LocalizedName: "Londo",
    EnglishName: "Londo",
    PrimaryPostalCode: "",
    Region: {
      ID: "AFR",
      LocalizedName: "Africa",
      EnglishName: "Africa",
    },
    Country: {
      ID: "TZ",
      LocalizedName: "Tanzania",
      EnglishName: "Tanzania",
    },
    AdministrativeArea: {
      ID: "21",
      LocalizedName: "Ruvuma",
      EnglishName: "Ruvuma",
      Level: 1,
      LocalizedType: "Region",
      EnglishType: "Region",
      CountryID: "TZ",
    },
    TimeZone: {
      Code: "EAT",
      Name: "Africa/Dar_es_Salaam",
      GmtOffset: 3,
      IsDaylightSaving: false,
      NextOffsetChange: null,
    },
    GeoPosition: {
      Latitude: -11.183,
      Longitude: 34.833,
      Elevation: {
        Metric: {
          Value: 1075,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 3526,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "MinuteCast",
    ],
  },
];
